silex_blog/src/Entity/Article.php
<?php


namespace Entity;


class Article
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $title;

    /**
     * @var string
     */
    private $content;

    /**
     * @var string
     */
    private $shortContent;

    /**
     * @var Category
     *
     */
    private $category;

    /**
     * @return Category
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param Category $category
     * @return $this
     */
    public function setCategory(Category $category)
    {
        $this->category = $category;
        return $this;
    }

    /**
     * @return int|null
     */
    public function getCategoryId(){
        if(!is_null($this->category)){
            return $this -> category -> getId();
        }

        return null;
    }

    /**
     * @return string
     */
    public function getCategoryName(){
        if(!is_null($this->category)){
            return $this -> category -> getName();
        }

        return '';
    }
    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     * @return Article
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param string $title
     * @return Article
     */
    public function setTitle($title)
    {
        $this->title = $title;
        return $this;
    }

    /**
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * @param string $content
     * @return Article
     */
    public function setContent($content)
    {
        $this->content = $content;
        return $this;
    }

    /**
     * @return string
     */
    public function getShortContent()
    {
        return $this->shortContent;
    }

    /**
     * @param string $shortContent
     * @return Article
     */
    public function setShortContent($shortContent)
    {
        $this->shortContent = $shortContent;
        return $this;
    }


}

silex_blog/src/Entity/Category.php
<?php
namespace Entity;

class Category
{
    /**
     *
     * @var int
     */
    private $id;
    
    /**
     *
     * @var string
     */
    private $name;
    
    /**
     * 
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * 
     * @return string
     */
    public function getName() 
    {
        return $this->name;
    }

    /**
     * 
     * @param int $id
     * @return $this
     */
    public function setId($id) 
    {
        $this->id = $id;
        
        return $this;
    }

    /**
     * 
     * @param string $name
     * @return $this
     */
    public function setName($name) 
    {
        $this->name = $name;
        
        return $this;
    }



}

silex_blog/src/Controller/Admin/ArticleController.php
<?php

namespace Controller\Admin;


use Controller\ControllerAbstract;
use Entity\Article;
use Entity\Category;

class ArticleController extends ControllerAbstract
{
    public function listAction()
    {
        $articles = $this->app['article.repository']->findAll();

        return $this->render(
            'admin/article/list.html.twig',
            ['articles' => $articles]
        );
    }

    public function editAction($id = null)
    {

        $categories = $this->app['category.repository'] -> findAll();

        if (!is_null($id)) {
            $article = $this->app['article.repository']->find($id);
        } else {
            $article = new Article();
            $article->setCategory(new Category());
        }

        if(!empty($_POST)){
            $article
                    ->setTitle($_POST['title'])
                    ->setContent($_POST['content'])
                    ->setShortContent($_POST['short_content'])

                    ->getCategory()->setId($_POST['category'])
                ;

            $this->app['article.repository'] -> save($article);
            $this -> addFlashMessage("L'article est enregistré");
            return $this -> redirectRoute('admin_articles');
        }

        return $this->render(
            'admin/article/edit.html.twig',
            [
                'article' => $article,
                'categories' => $categories
            ]
        );
    }

    public function deleteAction($id)
    {
        $article = $this->app['article.repository']->find($id);

        $this->app['article.repository']->delete($article);
        $this->addFlashMessage("L'article est supprimée");

        return $this->redirectRoute('admin_articles');
    }
}

silex_blog/src/Controller/Admin/CategoryController.php
<?php
namespace Controller\Admin;

use Controller\ControllerAbstract;
use Entity\Category;

class CategoryController extends ControllerAbstract
{
    public function listAction()
    {
        $categories = $this->app['category.repository']->findAll();
        
        return $this->render(
            'admin/category/list.html.twig', 
            ['categories' => $categories]
        );
    }
    
    public function editAction($id = null)
    {
        if (!is_null($id)) {
            $category = $this->app['category.repository']->find($id);
        } else {
            $category = new Category();
        }
        
        if (!empty($_POST)) {
            $category->setName($_POST['name']);
            
            $this->app['category.repository']->save($category);
            $this->addFlashMessage('La rubrique est enregistrée');
            
            return $this->redirectRoute('admin_categories');
        }
        
        return $this->render(
            'admin/category/edit.html.twig',
            ['category' => $category]
        );
    }
    
    public function deleteAction($id)
    {
        $category = $this->app['category.repository']->find($id);
        
        $this->app['category.repository']->delete($category);
        $this->addFlashMessage('La rubrique est supprimée');
        
        return $this->redirectRoute('admin_categories');
    }
}

silex_blog/src/Controller/ControllerAbstract.php
<?php
namespace Controller;

use Silex\Application;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Twig_Environment;

abstract class ControllerAbstract
{
    /**
     *
     * @var Application 
     */
    protected $app;

    /**
     *
     * @var Twig_Environment
     */
    protected $twig;

    /**
     *
     * @var Session
     */
    protected $session;
    /**
     * 
     * @param Application $app
     */
    public function __construct(Application $app)
    {
        $this->app = $app;
        $this->twig = $app['twig'];
        $this->session = $app['session'];
    }
    
    /**
     * Affiche une vue twig
     * 
     * @param string $view
     * @param array $parameters
     * @return string
     */
    public function render($view, $parameters = [])
    {
        return $this->twig->render($view, $parameters);
    }
    
    /**
     * Redirige vers une autre page en lui passant le nom de la route
     * 
     * @param string $routeName
     * @param array $parameters
     * @return Response
     */
    public function redirectRoute($routeName, array $parameters = [])
    {
        return $this->app->redirect(
            $this->app['url_generator']->generate($routeName, $parameters)
        );
    }
    
    public function addFlashMessage($message, $type = 'success')
    {
        $this->session->getFlashBag()->add($type, $message);
    }
}

silex_blog/src/Controller/IndexController.php
<?php
namespace Controller;

class IndexController extends ControllerAbstract
{
    public function indexAction()
    {
        $articles = $this -> app['article.repository'] -> findAll();
        return $this->render(
            'index.html.twig',
            ['articles' => $articles]
        );
    }

    public function categorieAction($id){
        $category = $this->app['category.repository']->find($id);
        $articles = $this->app['article.repository']->findByCategory($category);

        return $this->render(
            'category.html.twig',
                [
                    'category' => $category,
                    'articles' => $articles,
                ]
        );

    }

    public function categoriesAction() 
    {
        $categories = $this->app['category.repository']->findAll();
        
        return $this->render(
            'categories.html.twig', 
            ['categories' => $categories]
        );
    }
}

silex_blog/templates/article_list.html.twig
{% for article in articles %}
    <h3>{{ article.title }} <small>{{ article.categoryName }}</small></h3>
    <p><b>{{ article.shortContent }}</b></p>
    <p>{{ article.content }}</p>
    {% if not loop.last %}
        <hr>
    {% endif %}
{% endfor %}

silex_blog/templates/categories.html.twig
<ul class="nav navbar-nav">

    {% for category in categories %}
                <li><a href="{{ path('category', {id: category.id}) }}">{{ category.name }}</a></li>
    {% endfor %}

</ul>

silex_blog/templates/category.html.twig
{% extends "layout.html.twig" %}

{% block content %}
    <h2>{{ category.name }}</h2>
    {% include 'article_list.html.twig' %}
{% endblock %}

silex_blog/templates/index.html.twig
{% extends "layout.html.twig" %}

{% block content %}
    <h2>Accueil</h2>
    {% include 'article_list.html.twig' %}
{% endblock %}

silex_blog/templates/layout.html.twig
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{% block title '' %} - Blog</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="{{ asset('css/main.css') }}" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <nav class="navbar navbar-inverse">
            <div class="container">
                <a class="navbar-brand">Menu admin</a>
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{{ path('admin_categories') }}">Rubriques</a>
                    </li>
                    <li>
                        <a href="{{ path('admin_articles') }}">Articles</a>
                    </li>

                </ul>
            </div>
        </nav>
        <nav class="navbar navbar-default">
            <div class="container">
                <a class="navbar-brand" href="{{ path('homepage') }}">Blog</a>
                {# On affiche le rendu de la route categories #}
                {{ render(url('categories')) }}
            </div>
        </nav>
        <div class="container">
            {% for label, flashes in global.session.flashbag.all %}
                {% for flash in flashes %}
                    {% if label == 'error' %}
                        {% set label = 'danger' %}
                    {% endif %}
                    <div class="alert alert-{{ label }}">{{ flash }}</div>
                {% endfor %}
            {% endfor %}
            {% block content %}{% endblock %}
        </div>
        {% block javascripts %}
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        {% endblock %}
    </body>
</html>